//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalGroup_Omer_Karagulmez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CUSTOMERS
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
        public string Telephone { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string Identity_No { get; set; }
    }
}
